package model;
// Generated 27-dic-2018 18:11:38 by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente",
        schema = "dbo",
        catalog = "restoitsco"
)
public class Cliente implements java.io.Serializable {

    private int clienteId;
    private Empresa empresa;
    private String clienteNombre;
    private String cienteNumeroDocumento;
    private String clienteTelefono;
    private String clienteCorreo;
    private Date clienteFechaCreacion;
    private Date clienteFechaModificacion;
    private Character clienteEstado;
    private Set cabecerafacturas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(int clienteId, Empresa empresa) {
        this.clienteId = clienteId;
        this.empresa = empresa;
    }

    public Cliente(int clienteId, Empresa empresa, String clienteNombre, String cienteNumeroDocumento, String clienteTelefono, String clienteCorreo, Date clienteFechaCreacion, Date clienteFechaModificacion, Character clienteEstado, Set cabecerafacturas) {
        this.clienteId = clienteId;
        this.empresa = empresa;
        this.clienteNombre = clienteNombre;
        this.cienteNumeroDocumento = cienteNumeroDocumento;
        this.clienteTelefono = clienteTelefono;
        this.clienteCorreo = clienteCorreo;
        this.clienteFechaCreacion = clienteFechaCreacion;
        this.clienteFechaModificacion = clienteFechaModificacion;
        this.clienteEstado = clienteEstado;
        this.cabecerafacturas = cabecerafacturas;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "clienteId", unique = true, insertable = false, updatable = false)
    public int getClienteId() {
        return this.clienteId;
    }

    public void setClienteId(int clienteId) {
        this.clienteId = clienteId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "empresaId", nullable = false)
    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Column(name = "clienteNombre", length = 250)
    public String getClienteNombre() {
        return this.clienteNombre;
    }

    public void setClienteNombre(String clienteNombre) {
        this.clienteNombre = clienteNombre;
    }

    @Column(name = "cienteNumeroDocumento", length = 50, unique = true)
    public String getCienteNumeroDocumento() {
        return this.cienteNumeroDocumento;
    }

    public void setCienteNumeroDocumento(String cienteNumeroDocumento) {
        this.cienteNumeroDocumento = cienteNumeroDocumento;
    }

    @Column(name = "clienteTelefono", length = 50)
    public String getClienteTelefono() {
        return this.clienteTelefono;
    }

    public void setClienteTelefono(String clienteTelefono) {
        this.clienteTelefono = clienteTelefono;
    }

    @Column(name = "clienteCorreo", length = 150)
    public String getClienteCorreo() {
        return this.clienteCorreo;
    }

    public void setClienteCorreo(String clienteCorreo) {
        this.clienteCorreo = clienteCorreo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "clienteFechaCreacion", length = 23, insertable = false, updatable = false)
    public Date getClienteFechaCreacion() {
        return this.clienteFechaCreacion;
    }

    public void setClienteFechaCreacion(Date clienteFechaCreacion) {
        this.clienteFechaCreacion = clienteFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "clienteFechaModificacion", length = 23, insertable = false, updatable = false)
    public Date getClienteFechaModificacion() {
        return this.clienteFechaModificacion;
    }

    public void setClienteFechaModificacion(Date clienteFechaModificacion) {
        this.clienteFechaModificacion = clienteFechaModificacion;
    }

    @Column(name = "clienteEstado", length = 1)
    public Character getClienteEstado() {
        return this.clienteEstado;
    }

    public void setClienteEstado(Character clienteEstado) {
        this.clienteEstado = clienteEstado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
    public Set getCabecerafacturas() {
        return this.cabecerafacturas;
    }

    public void setCabecerafacturas(Set cabecerafacturas) {
        this.cabecerafacturas = cabecerafacturas;
    }

    @PrePersist
    public void prepersist() {
        if (clienteEstado == null) {
            clienteEstado = 'A';
        }
        if (clienteFechaCreacion == null) {
            Date date = new Date();
            clienteFechaCreacion = (new Timestamp(date.getTime()));
        }
    }
}
