package model;
// Generated 27-dic-2018 18:11:38 by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detallefactura generated by hbm2java
 */
@Entity
@Table(name = "detallefactura",
        schema = "dbo",
        catalog = "restoitsco"
)
public class Detallefactura implements java.io.Serializable {

    private int detallefacturaId;
    private Cabecerafactura cabecerafactura;
    private Menu menu;
    private Integer detallefacturaCantidad;
    private Date detallefacturaFechaCreacion;
    private Date detallefacturaFechaModificacion;
    private Character detallefacturaEstado;

    public Detallefactura() {
    }

    public Detallefactura(int detallefacturaId, Cabecerafactura cabecerafactura, Menu menu) {
        this.detallefacturaId = detallefacturaId;
        this.cabecerafactura = cabecerafactura;
        this.menu = menu;
    }

    public Detallefactura(int detallefacturaId, Cabecerafactura cabecerafactura, Menu menu, Integer detallefacturaCantidad, Date detallefacturaFechaCreacion, Date detallefacturaFechaModificacion, Character detallefacturaEstado) {
        this.detallefacturaId = detallefacturaId;
        this.cabecerafactura = cabecerafactura;
        this.menu = menu;
        this.detallefacturaCantidad = detallefacturaCantidad;
        this.detallefacturaFechaCreacion = detallefacturaFechaCreacion;
        this.detallefacturaFechaModificacion = detallefacturaFechaModificacion;
        this.detallefacturaEstado = detallefacturaEstado;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "detallefacturaId", unique = true, insertable = false, updatable = false)
    public int getDetallefacturaId() {
        return this.detallefacturaId;
    }

    public void setDetallefacturaId(int detallefacturaId) {
        this.detallefacturaId = detallefacturaId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cabecerafacturaId", nullable = false)
    public Cabecerafactura getCabecerafactura() {
        return this.cabecerafactura;
    }

    public void setCabecerafactura(Cabecerafactura cabecerafactura) {
        this.cabecerafactura = cabecerafactura;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "menuId", nullable = false)
    public Menu getMenu() {
        return this.menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    @Column(name = "detallefacturaCantidad")
    public Integer getDetallefacturaCantidad() {
        return this.detallefacturaCantidad;
    }

    public void setDetallefacturaCantidad(Integer detallefacturaCantidad) {
        this.detallefacturaCantidad = detallefacturaCantidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "detallefacturaFechaCreacion", length = 23, insertable = false, updatable = false)
    public Date getDetallefacturaFechaCreacion() {
        return this.detallefacturaFechaCreacion;
    }

    public void setDetallefacturaFechaCreacion(Date detallefacturaFechaCreacion) {
        this.detallefacturaFechaCreacion = detallefacturaFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "detallefacturaFechaModificacion", length = 23, insertable = false, updatable = false)
    public Date getDetallefacturaFechaModificacion() {
        return this.detallefacturaFechaModificacion;
    }

    public void setDetallefacturaFechaModificacion(Date detallefacturaFechaModificacion) {
        this.detallefacturaFechaModificacion = detallefacturaFechaModificacion;
    }

    @Column(name = "detallefacturaEstado", length = 1, insertable = false)
    public Character getDetallefacturaEstado() {
        return this.detallefacturaEstado;
    }

    public void setDetallefacturaEstado(Character detallefacturaEstado) {
        this.detallefacturaEstado = detallefacturaEstado;
    }

    @PrePersist
    public void prepersist() {
        if (detallefacturaEstado == null) {
            detallefacturaEstado = 'A';
        }
        if (detallefacturaFechaCreacion == null) {
            Date date = new Date();
            detallefacturaFechaCreacion = (new Timestamp(date.getTime()));
        }
    }
}
