package model;
// Generated 27-dic-2018 18:11:38 by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado",
        schema = "dbo",
        catalog = "restoitsco"
)
public class Empleado implements java.io.Serializable {

    private int empleadoId;
    private Cargo cargo;
    private Local local;
    private String empleadoPromerApellido;
    private String empleadoSegundoApellido;
    private String empleadoPrimernombre;
    private String empleadoSegundoNombre;
    private String empleadoNumeroDocumento;
    private Date empleadoFechaCreacion;
    private Date empleadoFechaModificacion;
    private String emleadoFoto;
    private Character empleadoEstado;
    private Set usuarios = new HashSet(0);

    public Empleado() {
    }

    public Empleado(int empleadoId, Cargo cargo, Local local) {
        this.empleadoId = empleadoId;
        this.cargo = cargo;
        this.local = local;
    }

    public Empleado(int empleadoId, Cargo cargo, Local local, String empleadoPromerApellido, String empleadoSegundoApellido, String empleadoPrimernombre, String empleadoSegundoNombre, String empleadoNumeroDocumento, Date empleadoFechaCreacion, Date empleadoFechaModificacion, String emleadoFoto, Character empleadoEstado, Set usuarios) {
        this.empleadoId = empleadoId;
        this.cargo = cargo;
        this.local = local;
        this.empleadoPromerApellido = empleadoPromerApellido;
        this.empleadoSegundoApellido = empleadoSegundoApellido;
        this.empleadoPrimernombre = empleadoPrimernombre;
        this.empleadoSegundoNombre = empleadoSegundoNombre;
        this.empleadoNumeroDocumento = empleadoNumeroDocumento;
        this.empleadoFechaCreacion = empleadoFechaCreacion;
        this.empleadoFechaModificacion = empleadoFechaModificacion;
        this.emleadoFoto = emleadoFoto;
        this.empleadoEstado = empleadoEstado;
        this.usuarios = usuarios;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "empleadoId", unique = true, insertable = false, updatable = false)
    public int getEmpleadoId() {
        return this.empleadoId;
    }

    public void setEmpleadoId(int empleadoId) {
        this.empleadoId = empleadoId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cargoId", nullable = false)
    public Cargo getCargo() {
        return this.cargo;
    }

    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "localId", nullable = false)
    public Local getLocal() {
        return this.local;
    }

    public void setLocal(Local local) {
        this.local = local;
    }

    @Column(name = "empleadoPromerApellido", length = 150)
    public String getEmpleadoPromerApellido() {
        return this.empleadoPromerApellido;
    }

    public void setEmpleadoPromerApellido(String empleadoPromerApellido) {
        this.empleadoPromerApellido = empleadoPromerApellido;
    }

    @Column(name = "empleadoSegundoApellido", length = 150)
    public String getEmpleadoSegundoApellido() {
        return this.empleadoSegundoApellido;
    }

    public void setEmpleadoSegundoApellido(String empleadoSegundoApellido) {
        this.empleadoSegundoApellido = empleadoSegundoApellido;
    }

    @Column(name = "empleadoPrimernombre", length = 150)
    public String getEmpleadoPrimernombre() {
        return this.empleadoPrimernombre;
    }

    public void setEmpleadoPrimernombre(String empleadoPrimernombre) {
        this.empleadoPrimernombre = empleadoPrimernombre;
    }

    @Column(name = "empleadoSegundoNombre", length = 150)
    public String getEmpleadoSegundoNombre() {
        return this.empleadoSegundoNombre;
    }

    public void setEmpleadoSegundoNombre(String empleadoSegundoNombre) {
        this.empleadoSegundoNombre = empleadoSegundoNombre;
    }

    @Column(name = "empleadoNumeroDocumento", length = 50, unique = true)
    public String getEmpleadoNumeroDocumento() {
        return this.empleadoNumeroDocumento;
    }

    public void setEmpleadoNumeroDocumento(String empleadoNumeroDocumento) {
        this.empleadoNumeroDocumento = empleadoNumeroDocumento;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "empleadoFechaCreacion", length = 23, insertable = false, updatable = false)
    public Date getEmpleadoFechaCreacion() {
        return this.empleadoFechaCreacion;
    }

    public void setEmpleadoFechaCreacion(Date empleadoFechaCreacion) {
        this.empleadoFechaCreacion = empleadoFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "empleadoFechaModificacion", length = 23, insertable = false, updatable = false)
    public Date getEmpleadoFechaModificacion() {
        return this.empleadoFechaModificacion;
    }

    public void setEmpleadoFechaModificacion(Date empleadoFechaModificacion) {
        this.empleadoFechaModificacion = empleadoFechaModificacion;
    }

    @Column(name = "emleadoFoto", length = 500)
    public String getEmleadoFoto() {
        return this.emleadoFoto;
    }

    public void setEmleadoFoto(String emleadoFoto) {
        this.emleadoFoto = emleadoFoto;
    }

    @Column(name = "empleadoEstado", length = 1, insertable = false)
    public Character getEmpleadoEstado() {
        return this.empleadoEstado;
    }

    public void setEmpleadoEstado(Character empleadoEstado) {
        this.empleadoEstado = empleadoEstado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empleado")
    public Set getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    @PrePersist
    public void prepersist() {
        if (empleadoEstado == null) {
            empleadoEstado = 'A';
        }
        if (empleadoFechaCreacion == null) {
            Date date = new Date();
            empleadoFechaCreacion = (new Timestamp(date.getTime()));
        }
    }
}
