package model;
// Generated 11-dic-2018 10:09:37 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OpcionXperfil generated by hbm2java
 */
@Entity
@Table(name = "opcionXPerfil",
         schema = "dbo",
         catalog = "restoitsco"
)
public class OpcionXperfil implements java.io.Serializable {

    private int opcionPerfilId;
    private Opcion opcion;
    private Perfil perfil;
    private Date opcionPerfilFechaCreacion;
    private Date opcionPerfilFechaModificacion;
    private Character opcionPerfilEstado;

    public OpcionXperfil() {
    }

    public OpcionXperfil(int opcionPerfilId, Opcion opcion, Perfil perfil) {
        this.opcionPerfilId = opcionPerfilId;
        this.opcion = opcion;
        this.perfil = perfil;
    }

    public OpcionXperfil(int opcionPerfilId, Opcion opcion, Perfil perfil, Date opcionPerfilFechaCreacion, Date opcionPerfilFechaModificacion, Character opcionPerfilEstado) {
        this.opcionPerfilId = opcionPerfilId;
        this.opcion = opcion;
        this.perfil = perfil;
        this.opcionPerfilFechaCreacion = opcionPerfilFechaCreacion;
        this.opcionPerfilFechaModificacion = opcionPerfilFechaModificacion;
        this.opcionPerfilEstado = opcionPerfilEstado;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "opcionPerfilId", unique = true, insertable = false, updatable = false)
    public int getOpcionPerfilId() {
        return this.opcionPerfilId;
    }

    public void setOpcionPerfilId(int opcionPerfilId) {
        this.opcionPerfilId = opcionPerfilId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "opcionId", nullable = false)
    public Opcion getOpcion() {
        return this.opcion;
    }

    public void setOpcion(Opcion opcion) {
        this.opcion = opcion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "perfilId", nullable = false)
    public Perfil getPerfil() {
        return this.perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "opcionPerfilFechaCreacion", length = 23, insertable = false, updatable = false)
    public Date getOpcionPerfilFechaCreacion() {
        return this.opcionPerfilFechaCreacion;
    }

    public void setOpcionPerfilFechaCreacion(Date opcionPerfilFechaCreacion) {
        this.opcionPerfilFechaCreacion = opcionPerfilFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "opcionPerfilFechaModificacion", length = 23, insertable = false, updatable = false)
    public Date getOpcionPerfilFechaModificacion() {
        return this.opcionPerfilFechaModificacion;
    }

    public void setOpcionPerfilFechaModificacion(Date opcionPerfilFechaModificacion) {
        this.opcionPerfilFechaModificacion = opcionPerfilFechaModificacion;
    }

    @Column(name = "opcionPerfilEstado", length = 1, insertable = false)
    public Character getOpcionPerfilEstado() {
        return this.opcionPerfilEstado;
    }

    public void setOpcionPerfilEstado(Character opcionPerfilEstado) {
        this.opcionPerfilEstado = opcionPerfilEstado;
    }

}
