package model;
// Generated 27-dic-2018 18:11:38 by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto",
        schema = "dbo",
        catalog = "restoitsco"
)
public class Producto implements java.io.Serializable {

    private int productoId;
    private String productoNombre;
    private String productoDetalle;
    private Date productoFechaCreacion;
    private Date productoFechaModificacion;
    private Character productoEstado;
    private Set inventarios = new HashSet(0);

    public Producto() {
    }

    public Producto(int productoId) {
        this.productoId = productoId;
    }

    public Producto(int productoId, String productoNombre, String productoDetalle, Date productoFechaCreacion, Date productoFechaModificacion, Character productoEstado, Set inventarios) {
        this.productoId = productoId;
        this.productoNombre = productoNombre;
        this.productoDetalle = productoDetalle;
        this.productoFechaCreacion = productoFechaCreacion;
        this.productoFechaModificacion = productoFechaModificacion;
        this.productoEstado = productoEstado;
        this.inventarios = inventarios;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "productoId", unique = true, insertable = false, updatable = false)
    public int getProductoId() {
        return this.productoId;
    }

    public void setProductoId(int productoId) {
        this.productoId = productoId;
    }

    @Column(name = "productoNombre", length = 150)
    public String getProductoNombre() {
        return this.productoNombre;
    }

    public void setProductoNombre(String productoNombre) {
        this.productoNombre = productoNombre;
    }

    @Column(name = "productoDetalle", length = 200)
    public String getProductoDetalle() {
        return this.productoDetalle;
    }

    public void setProductoDetalle(String productoDetalle) {
        this.productoDetalle = productoDetalle;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "productoFechaCreacion", length = 23, insertable = false, updatable = false)
    public Date getProductoFechaCreacion() {
        return this.productoFechaCreacion;
    }

    public void setProductoFechaCreacion(Date productoFechaCreacion) {
        this.productoFechaCreacion = productoFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "productoFechaModificacion", length = 23, insertable = false, updatable = false)
    public Date getProductoFechaModificacion() {
        return this.productoFechaModificacion;
    }

    public void setProductoFechaModificacion(Date productoFechaModificacion) {
        this.productoFechaModificacion = productoFechaModificacion;
    }

    @Column(name = "productoEstado", length = 1, insertable = false)
    public Character getProductoEstado() {
        return this.productoEstado;
    }

    public void setProductoEstado(Character productoEstado) {
        this.productoEstado = productoEstado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
    public Set getInventarios() {
        return this.inventarios;
    }

    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }

    @PrePersist
    public void prepersist() {
        if (productoEstado == null) {
            productoEstado = 'A';
        }
        if (productoFechaCreacion == null) {
            Date date = new Date();
            productoFechaCreacion = (new Timestamp(date.getTime()));
        }
    }
}
