package model;
// Generated 27-dic-2018 18:11:38 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TempInventario generated by hbm2java
 */
@Entity
@Table(name = "tempInventario",
         schema = "dbo",
         catalog = "restoitsco"
)
public class TempInventario implements java.io.Serializable {

    private int id;
    private int localId;
    private int productoId;
    private double cantidad;
    private String local;
    private String producto;

    public TempInventario() {
    }

    public TempInventario(int id, int localId, int productoId, double cantidad, String local, String producto) {
        this.id = id;
        this.localId = localId;
        this.productoId = productoId;
        this.cantidad = cantidad;
        this.local = local;
        this.producto = producto;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, insertable = false, updatable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "localId", nullable = false)
    public int getLocalId() {
        return this.localId;
    }

    public void setLocalId(int localId) {
        this.localId = localId;
    }

    @Column(name = "productoId", nullable = false)
    public int getProductoId() {
        return this.productoId;
    }

    public void setProductoId(int productoId) {
        this.productoId = productoId;
    }

    @Column(name = "cantidad", nullable = false, precision = 53, scale = 0)
    public double getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }

    @Column(name = "local", nullable = false, length = 150)
    public String getLocal() {
        return this.local;
    }

    public void setLocal(String local) {
        this.local = local;
    }

    @Column(name = "producto", nullable = false, length = 150)
    public String getProducto() {
        return this.producto;
    }

    public void setProducto(String producto) {
        this.producto = producto;
    }

}
