package model;
// Generated 11-dic-2018 10:09:37 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario",
        schema = "dbo",
        catalog = "restoitsco"
)
public class Usuario implements java.io.Serializable {

    private int usuarioId;
    private Empleado empleado;
    private Perfil perfil;
    private String usuarioNombre;
    private String usuarioClave;
    private Date usuarioFechaCreacion;
    private Date usuarioFechaModificacion;
    private Character usuarioEstado;
    private Set cabecerafacturas = new HashSet(0);

    public Usuario() {
    }

    public Usuario(int usuarioId, Empleado empleado, Perfil perfil) {
        this.usuarioId = usuarioId;
        this.empleado = empleado;
        this.perfil = perfil;
    }

    public Usuario(int usuarioId, Empleado empleado, Perfil perfil, String usuarioNombre, String usuarioClave, Date usuarioFechaCreacion, Date usuarioFechaModificacion, Character usuarioEstado, Set cabecerafacturas) {
        this.usuarioId = usuarioId;
        this.empleado = empleado;
        this.perfil = perfil;
        this.usuarioNombre = usuarioNombre;
        this.usuarioClave = usuarioClave;
        this.usuarioFechaCreacion = usuarioFechaCreacion;
        this.usuarioFechaModificacion = usuarioFechaModificacion;
        this.usuarioEstado = usuarioEstado;
        this.cabecerafacturas = cabecerafacturas;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "usuarioId", unique = true, nullable = false)
    public int getUsuarioId() {
        return this.usuarioId;
    }

    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "empleadoId", nullable = false)
    public Empleado getEmpleado() {
        return this.empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "perfilId", nullable = false)
    public Perfil getPerfil() {
        return this.perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    @Column(name = "usuarioNombre", length = 50)
    public String getUsuarioNombre() {
        return this.usuarioNombre;
    }

    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }

    @Column(name = "usuarioClave", length = 50)
    public String getUsuarioClave() {
        return this.usuarioClave;
    }

    public void setUsuarioClave(String usuarioClave) {
        this.usuarioClave = usuarioClave;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "usuarioFechaCreacion", length = 23, insertable = false, updatable = false)
    public Date getUsuarioFechaCreacion() {
        return this.usuarioFechaCreacion;
    }

    public void setUsuarioFechaCreacion(Date usuarioFechaCreacion) {
        this.usuarioFechaCreacion = usuarioFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "usuarioFechaModificacion", length = 23, insertable = false, updatable = false)
    public Date getUsuarioFechaModificacion() {
        return this.usuarioFechaModificacion;
    }

    public void setUsuarioFechaModificacion(Date usuarioFechaModificacion) {
        this.usuarioFechaModificacion = usuarioFechaModificacion;
    }

    @Column(name = "usuarioEstado", length = 1, insertable = false)
    public Character getUsuarioEstado() {
        return this.usuarioEstado;
    }

    public void setUsuarioEstado(Character usuarioEstado) {
        this.usuarioEstado = usuarioEstado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    public Set getCabecerafacturas() {
        return this.cabecerafacturas;
    }

    public void setCabecerafacturas(Set cabecerafacturas) {
        this.cabecerafacturas = cabecerafacturas;
    }

}
